---
# tasks file for users

- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: Install required software
  ansible.builtin.package:
    name: "{{ users_requirements }}"
    state: present

- name: Loop over users_groups
  ansible.builtin.include_tasks:
    file: group.yml
  loop: "{{ users_groups }}"
  loop_control:
    label: "{{ group.name }}"
    loop_var: group
  when:
    - users_groups is defined

- name: Loop over users
  ansible.builtin.include_tasks:
    file: user.yml
  loop: "{{ users }}"
  loop_control:
    label: "{{ user.name }}"
    loop_var: user
  when:
    - users is defined

- name: Manage cron permission
  ansible.builtin.template:
    src: cron.allow.j2
    dest: /etc/cron.allow
    mode: "0644"
  when:
    - users_cron_allow

- name: Check existence of /etc/cron.allow
  ansible.builtin.file:
    path: /etc/cron.allow
    state: absent
  when:
    - not users_cron_allow

- name: Ensure the sudoers.d directory is checked for user sudoers files (will be put after EOF if not exists)
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    line: "@includedir /etc/sudoers.d"
